"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { dbListSchemas } from "@/lib/db-platform";
import { dbImportSchema } from "@/lib/tauri";
import type { DbImportResult } from "@/lib/tauri";
import { useIdeFsStore } from "@/stores/ide-fs-store";
import {
    AlertCircle,
    CheckCircle2,
    ChevronDown,
    ChevronRight,
    Database,
    Download,
    FileCode,
    Loader2,
    RefreshCw,
    Table,
    X,
    Zap,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
} from "@/components/ui/dialog";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { createDefaultDocData, markdownToDocData, serializeDocData } from "@/lib/doc-editor";
import { generateSchemaDocContent } from "@/lib/schema-doc-ai";
import { notifySchemaDocFileUpdated } from "@/stores/schema-doc-gen-store";
import { useSettingsStore } from "@/stores/settings-store";

// ── Types ─────────────────────────────────────────────────────────────────────

type ImportPhase = "idle" | "loading-schemas" | "selecting" | "importing" | "done" | "error";

/** Turn raw backend errors into a user-friendly title and description (shadcn-style). */
function formatImportError(raw: string): { title: string; description: string; technical?: string } {
    const normalized = raw.trim();
    const stripDbPrefix = (s: string) => s.replace(/^db error:?\s*/i, "").trim();
    const technical = normalized.length > 200 ? normalized : undefined;

    if (/functions?\s+query\s+error/i.test(normalized)) {
        const schemaMatch = normalized.match(/for\s+['"]?(\w+)['"]?/i);
        const schema = schemaMatch ? schemaMatch[1] : "the schema";
        return {
            title: "Couldn’t load database functions",
            description: `We couldn’t read functions for schema "${schema}". This often means the database user doesn’t have permission to read the pg_proc catalog, or the connection was interrupted.`,
            technical: stripDbPrefix(normalized),
        };
    }
    if (/tables?\s+query\s+error/i.test(normalized)) {
        const schemaMatch = normalized.match(/for\s+['"]?(\w+)['"]?/i);
        const schema = schemaMatch ? schemaMatch[1] : "the schema";
        return {
            title: "Couldn’t load tables",
            description: `We couldn’t read tables for schema "${schema}". Check that the database is reachable and your user has permission to read the information_schema or pg_catalog.`,
            technical: stripDbPrefix(normalized),
        };
    }
    if (/connection|timeout|refused|ECONNREFUSED/i.test(normalized)) {
        return {
            title: "Connection problem",
            description: "We couldn’t reach the database. Check that it’s running, the host and port are correct, and nothing is blocking the connection (e.g. firewall).",
            technical: stripDbPrefix(normalized),
        };
    }
    if (/permission|denied|access/i.test(normalized)) {
        return {
            title: "Permission denied",
            description: "The database user doesn’t have the required permissions to read schema metadata. Grant SELECT on the relevant system catalogs or use a user with broader access.",
            technical: stripDbPrefix(normalized),
        };
    }
    if (/authentication|password|auth/i.test(normalized)) {
        return {
            title: "Authentication failed",
            description: "The database rejected the credentials. Check the username and password and try again.",
            technical: stripDbPrefix(normalized),
        };
    }

    return {
        title: "Import failed",
        description: "Something went wrong while reading the database schema. Try again or check the connection and permissions.",
        technical: stripDbPrefix(normalized),
    };
}

interface SchemaOption {
    name: string;
    tableCount: number;
    selected: boolean;
}

interface ImportProgress {
    current: number;
    total: number;
    message: string;
}

// ── File tree builder ─────────────────────────────────────────────────────────

export interface ReadmeNodeRef {
    schemaName: string;
    nodeId: string;
}

function buildFileTree(
    result: DbImportResult,
    connectionId: string,
): { folderCount: number; fileCount: number; readmeNodeIds: ReadmeNodeRef[] } {
    const { createNode, setExpanded } = useIdeFsStore.getState();
    let folderCount = 0;
    let fileCount = 0;
    const readmeNodeIds: ReadmeNodeRef[] = [];

    const now = Date.now();
    const header = (label: string) =>
        `-- ================================================================\n-- ${label}\n-- Generated by pgStudio · ${new Date(now).toISOString()}\n-- ================================================================\n\n`;

    for (const schema of result.schemas) {
        // Root schema folder
        const schemaFolder = createNode(connectionId, schema.schema, "folder", null);
        setExpanded(schemaFolder.id, true);
        folderCount++;

        // ── Tables ────────────────────────────────────────────────────────────
        if (schema.tables.length > 0) {
            const tablesFolder = createNode(connectionId, "tables", "folder", schemaFolder.id);
            setExpanded(tablesFolder.id, true);
            folderCount++;
            for (const tbl of schema.tables) {
                const rows = typeof tbl.estimated_rows === "number" && tbl.estimated_rows > 0
                    ? `-- Estimated rows: ~${tbl.estimated_rows.toLocaleString()}\n`
                    : "";
                const comment = tbl.comment ? `-- ${tbl.comment}\n` : "";
                const content = `${header(`Table: ${schema.schema}.${tbl.name}`)}${comment}${rows}\n${tbl.ddl ?? ""}\n`;
                createNode(connectionId, `${tbl.name}.sql`, "file", tablesFolder.id, content);
                fileCount++;
            }
        }

        // ── Views ─────────────────────────────────────────────────────────────
        if (schema.views.length > 0) {
            const viewsFolder = createNode(connectionId, "views", "folder", schemaFolder.id);
            folderCount++;
            for (const view of schema.views) {
                const kind = view.is_materialized ? "Materialized View" : "View";
                const content = `${header(`${kind}: ${schema.schema}.${view.name}`)}\n${view.ddl ?? ""}\n`;
                createNode(connectionId, `${view.name}.sql`, "file", viewsFolder.id, content);
                fileCount++;
            }
        }

        // ── Functions ─────────────────────────────────────────────────────────
        if (schema.functions.length > 0) {
            const fnFolder = createNode(connectionId, "functions", "folder", schemaFolder.id);
            folderCount++;
            for (const fn_ of schema.functions) {
                const safeName = fn_.arguments
                    ? `${fn_.name}__${fn_.arguments.replace(/[^a-z0-9_]/gi, "_").slice(0, 36)}`
                    : fn_.name;
                const content = `${header(`${fn_.kind}: ${schema.schema}.${fn_.name}(${fn_.arguments})`)}\n${fn_.ddl ?? ""}\n`;
                createNode(connectionId, `${safeName}.sql`, "file", fnFolder.id, content);
                fileCount++;
            }
        }

        // ── Indexes (non-PK only) ─────────────────────────────────────────────
        const nonPkIndexes = schema.indexes.filter((i) => !i.is_primary);
        if (nonPkIndexes.length > 0) {
            const idxFolder = createNode(connectionId, "indexes", "folder", schemaFolder.id);
            folderCount++;
            const byTable = new Map<string, typeof nonPkIndexes>();
            for (const idx of nonPkIndexes) {
                const arr = byTable.get(idx.table_name) ?? [];
                arr.push(idx);
                byTable.set(idx.table_name, arr);
            }
            for (const [tableName, idxes] of byTable) {
                const tableIdxFolder = createNode(connectionId, tableName, "folder", idxFolder.id);
                for (const idx of idxes) {
                    const unique = idx.is_unique ? " UNIQUE" : "";
                    const content = `${header(`Index${unique}: ${idx.name} on ${schema.schema}.${tableName}`)}\n${idx.ddl ?? ""};\n`;
                    createNode(connectionId, `${idx.name}.sql`, "file", tableIdxFolder.id, content);
                    fileCount++;
                }
            }
        }

        // ── Triggers ──────────────────────────────────────────────────────────
        if (schema.triggers.length > 0) {
            const trigFolder = createNode(connectionId, "triggers", "folder", schemaFolder.id);
            folderCount++;
            for (const trig of schema.triggers) {
                const content = `${header(`Trigger: ${trig.name} on ${schema.schema}.${trig.table_name}`)}\n${trig.ddl ?? ""}\n`;
                createNode(connectionId, `${trig.name}.sql`, "file", trigFolder.id, content);
                fileCount++;
            }
        }

        // ── Sequences ─────────────────────────────────────────────────────────
        if (schema.sequences.length > 0) {
            const seqFolder = createNode(connectionId, "sequences", "folder", schemaFolder.id);
            folderCount++;
            for (const seq of schema.sequences) {
                const content = `${header(`Sequence: ${schema.schema}.${seq.name}`)}\n${seq.ddl ?? ""}\n`;
                createNode(connectionId, `${seq.name}.sql`, "file", seqFolder.id, content);
                fileCount++;
            }
        }

        // ── README.doc (placeholder; AI fills in background) ──────────────────
        const placeholderDoc = createDefaultDocData();
        if (placeholderDoc.content && placeholderDoc.content.length > 0 && placeholderDoc.content[0]) {
            placeholderDoc.content[0] = {
                type: "paragraph",
                content: [{ type: "text", text: "Generating documentation…" }],
            };
        }
        const readmeNode = createNode(
            connectionId,
            "README.doc",
            "file",
            schemaFolder.id,
            serializeDocData(placeholderDoc)
        );
        readmeNodeIds.push({ schemaName: schema.schema, nodeId: readmeNode.id });
        fileCount++;
    }

    return { folderCount, fileCount, readmeNodeIds };
}

// ── Schema selector row ───────────────────────────────────────────────────────

function SchemaRow({ schema, onToggle }: { schema: SchemaOption; onToggle: (name: string) => void }) {
    return (
        <div
            className={cn(
                "flex items-center gap-2.5 px-3 py-2 rounded-md cursor-pointer transition-colors group",
                schema.selected ? "bg-white/10 text-white" : "hover:bg-white/10 text-white/70"
            )}
            onClick={() => onToggle(schema.name)}
        >
            <Checkbox
                checked={schema.selected}
                onCheckedChange={() => onToggle(schema.name)}
                className="shrink-0 h-3.5 w-3.5"
                onClick={(e) => e.stopPropagation()}
            />
            <Database className={cn("h-3.5 w-3.5 shrink-0", schema.selected ? "text-white/80" : "text-white/40")} />
            <span className="text-[12.5px] flex-1 font-mono">{schema.name}</span>
            <Badge
                variant="outline"
                className="text-[9px] h-4 px-1.5 text-white/40 border-white/20 font-mono"
            >
                {schema.tableCount}t
            </Badge>
        </div>
    );
}

// ── Result summary ─────────────────────────────────────────────────────────────

function ResultSummary({ result }: { result: DbImportResult }) {
    const [expanded, setExpanded] = useState<Set<string>>(new Set());

    const toggle = (schema: string) => setExpanded((prev) => {
        const next = new Set(prev);
        if (next.has(schema)) next.delete(schema); else next.add(schema);
        return next;
    });

    const stats = [
        { label: "Tables", value: result.total_tables, icon: <Table className="h-3.5 w-3.5" />, color: "text-sky-400" },
        { label: "Views", value: result.total_views, icon: <FileCode className="h-3.5 w-3.5" />, color: "text-violet-400" },
        { label: "Functions", value: result.total_functions, icon: <Zap className="h-3.5 w-3.5" />, color: "text-amber-400" },
        { label: "Indexes", value: result.total_indexes, icon: <Database className="h-3.5 w-3.5" />, color: "text-emerald-400" },
    ].filter((s) => s.value > 0);

    return (
        <div className="space-y-3">
            {/* Stat pills — black dialog: white text */}
            {stats.length > 0 && (
                <div className="grid grid-cols-2 gap-1.5">
                    {stats.map((stat) => (
                        <div
                            key={stat.label}
                            className="flex items-center gap-2 rounded-lg border border-white/15 bg-white/5 px-3 py-2"
                        >
                            <span className={cn("shrink-0", stat.color)}>{stat.icon}</span>
                            <div>
                                <p className="text-base font-semibold leading-none tabular-nums text-white">{stat.value}</p>
                                <p className="text-[10px] text-white/50 mt-0.5">{stat.label}</p>
                            </div>
                        </div>
                    ))}
                </div>
            )}

            {/* Per-schema tree */}
            <div className="space-y-1">
                {result.schemas.map((s) => {
                    const nonPkIdx = s.indexes.filter((i) => !i.is_primary).length;
                    return (
                        <div key={s.schema} className="rounded-lg border border-white/15 overflow-hidden">
                            <button
                                className="w-full flex items-center gap-2 px-3 py-2 hover:bg-white/10 transition-colors text-left"
                                onClick={() => toggle(s.schema)}
                            >
                                {expanded.has(s.schema)
                                    ? <ChevronDown className="h-3 w-3 text-white/40 shrink-0" />
                                    : <ChevronRight className="h-3 w-3 text-white/40 shrink-0" />}
                                <Database className="h-3.5 w-3.5 text-white/40 shrink-0" />
                                <span className="font-mono text-[12px] text-white/80 flex-1">{s.schema}</span>
                                <div className="flex gap-1 shrink-0">
                                    {s.tables.length > 0 && <Badge variant="outline" className="text-[9px] h-4 px-1 text-sky-400 border-sky-400/20">{s.tables.length}T</Badge>}
                                    {s.views.length > 0 && <Badge variant="outline" className="text-[9px] h-4 px-1 text-violet-400 border-violet-400/20">{s.views.length}V</Badge>}
                                    {s.functions.length > 0 && <Badge variant="outline" className="text-[9px] h-4 px-1 text-amber-400 border-amber-400/20">{s.functions.length}F</Badge>}
                                    {nonPkIdx > 0 && <Badge variant="outline" className="text-[9px] h-4 px-1 text-emerald-400 border-emerald-400/20">{nonPkIdx}I</Badge>}
                                </div>
                            </button>

                            {expanded.has(s.schema) && s.tables.length > 0 && (
                                <div className="px-3 pb-2 pt-1 bg-white/5 space-y-px">
                                    {s.tables.map((t) => {
                                        const rows = typeof t.estimated_rows === "number" && t.estimated_rows > 0
                                            ? t.estimated_rows.toLocaleString()
                                            : null;
                                        return (
                                            <div key={t.name} className="flex items-center gap-1.5 py-[1px]">
                                                <svg className="h-3.5 w-3.5 shrink-0" viewBox="0 0 16 16" fill="none">
                                                    <rect x="1" y="3" width="14" height="10" rx="1.5" fill="#38bdf8" opacity="0.15" />
                                                    <ellipse cx="8" cy="5.5" rx="5" ry="1.8" fill="#38bdf8" opacity="0.7" />
                                                    <path d="M3 5.5v5c0 1 2.24 1.8 5 1.8s5-.8 5-1.8v-5" stroke="#38bdf8" strokeWidth="1.1" strokeLinecap="round" />
                                                    <path d="M3 8c0 1 2.24 1.8 5 1.8s5-.8 5-1.8" stroke="#38bdf8" strokeWidth="1.1" strokeLinecap="round" />
                                                </svg>
                                                <span className="font-mono text-[11px] text-white/70 flex-1 truncate">{t.name}</span>
                                                {rows && <span className="text-[9px] text-white/30 shrink-0">~{rows}</span>}
                                            </div>
                                        );
                                    })}
                                </div>
                            )}
                        </div>
                    );
                })}
            </div>
        </div>
    );
}

// ── Circular progress ─────────────────────────────────────────────────────────

function CircularProgress({ value, max }: { value: number; max: number }) {
    const r = 24;
    const circ = 2 * Math.PI * r;
    const progress = max > 0 ? Math.min(value / max, 1) : 0;
    return (
        <svg width="64" height="64" viewBox="0 0 56 56" className="-rotate-90">
            <circle cx="28" cy="28" r={r} fill="none" stroke="currentColor" strokeWidth="3" className="text-white/20" />
            <circle
                cx="28" cy="28" r={r} fill="none" stroke="currentColor" strokeWidth="3"
                strokeDasharray={circ}
                strokeDashoffset={circ * (1 - progress)}
                className="text-white/70 transition-[stroke-dashoffset] duration-500 ease-out"
                strokeLinecap="round"
            />
        </svg>
    );
}

// ── Main dialog ───────────────────────────────────────────────────────────────

export interface SchemaImporterProps {
    open: boolean;
    onClose: () => void;
    connectionId: string;
    databaseName: string;
}

export function SchemaImporter({ open, onClose, connectionId, databaseName }: SchemaImporterProps) {
    const [phase, setPhase] = useState<ImportPhase>("idle");
    const [schemas, setSchemas] = useState<SchemaOption[]>([]);
    const [progress, setProgress] = useState<ImportProgress | null>(null);
    const [importResult, setImportResult] = useState<DbImportResult | null>(null);
    const [error, setError] = useState<string | null>(null);
    const progressTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);

    // Reset and load when dialog opens
    useEffect(() => {
        if (!open) return;
        setPhase("loading-schemas");
        setImportResult(null);
        setError(null);
        setProgress(null);
        loadSchemas();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [open, connectionId]);

    // Cleanup timer on unmount
    useEffect(() => () => {
        if (progressTimerRef.current) clearInterval(progressTimerRef.current);
    }, []);

    const loadSchemas = async () => {
        try {
            const list = await dbListSchemas(connectionId);
            setSchemas(
                list.map((s) => ({
                    name: s.name,
                    tableCount: Number(s.table_count ?? 0),
                    selected: s.name === "public",
                }))
            );
            setPhase("selecting");
        } catch (e) {
            setError(String(e));
            setPhase("error");
        }
    };

    const allSelected = schemas.length > 0 && schemas.every((s) => s.selected);
    const selectedCount = schemas.filter((s) => s.selected).length;

    const toggleSchema = (name: string) =>
        setSchemas((prev) => prev.map((s) => (s.name === name ? { ...s, selected: !s.selected } : s)));

    const toggleAll = () =>
        setSchemas((prev) => prev.map((s) => ({ ...s, selected: !allSelected })));

    const handleImport = useCallback(async () => {
        const selected = schemas.filter((s) => s.selected).map((s) => s.name);
        if (selected.length === 0) {
            toast.error("Select at least one schema");
            return;
        }

        setPhase("importing");
        setProgress({ current: 0, total: selected.length, message: "Connecting to database…" });

        // Animated progress — advances every ~500ms while waiting for the Rust call
        let idx = 0;
        progressTimerRef.current = setInterval(() => {
            idx = Math.min(idx + 1, selected.length);
            setProgress({
                current: idx,
                total: selected.length,
                message: idx < selected.length
                    ? `Introspecting "${selected[idx - 1]}"…`
                    : "Building file structure…",
            });
            if (idx >= selected.length && progressTimerRef.current) {
                clearInterval(progressTimerRef.current);
                progressTimerRef.current = null;
            }
        }, 500);

        try {
            const result = await dbImportSchema(connectionId, selected);

            if (progressTimerRef.current) {
                clearInterval(progressTimerRef.current);
                progressTimerRef.current = null;
            }

            setProgress({ current: selected.length, total: selected.length, message: "Building file structure…" });

            // Build file tree (synchronous, fast)
            const { fileCount, readmeNodeIds } = buildFileTree(result, connectionId);

            setImportResult(result);
            setPhase("done");
            toast.success(
                `Imported ${result.total_tables} tables · ${result.total_functions} functions · ${fileCount} files created`,
                { duration: 4000 }
            );

            // Background: generate AI schema docs for each README.doc
            const apiKey = useSettingsStore.getState().geminiApiKey?.trim();
            if (apiKey && readmeNodeIds.length > 0) {
                const { updateContent } = useIdeFsStore.getState();
                const schemaByName = new Map(result.schemas.map((s) => [s.schema, s]));
                Promise.allSettled(
                    readmeNodeIds.map(async ({ schemaName, nodeId }) => {
                        const schema = schemaByName.get(schemaName);
                        if (!schema) return;
                        try {
                            const markdown = await generateSchemaDocContent(schema, result.database);
                            const docData = markdownToDocData(markdown);
                            const docJson = serializeDocData(docData);
                            updateContent(nodeId, docJson);
                            notifySchemaDocFileUpdated(nodeId, docJson);
                        } catch (e) {
                            const msg = e instanceof Error ? e.message : String(e);
                            toast.error(`Documentation failed for schema "${schemaName}"`, { description: msg });
                            const errorDoc = createDefaultDocData();
                            if (errorDoc.content?.[0]) {
                                errorDoc.content[0] = {
                                    type: "paragraph",
                                    content: [{ type: "text", text: `Documentation generation failed: ${msg}` }],
                                };
                            }
                            updateContent(nodeId, serializeDocData(errorDoc));
                        }
                    })
                );
            }
        } catch (e) {
            if (progressTimerRef.current) {
                clearInterval(progressTimerRef.current);
                progressTimerRef.current = null;
            }
            setError(String(e));
            setPhase("error");
        }
    }, [schemas, connectionId]);

    const handleClose = () => {
        if (progressTimerRef.current) clearInterval(progressTimerRef.current);
        onClose();
    };

    const errorFormatted = error ? formatImportError(error) : null;

    return (
        <Dialog open={open} onOpenChange={(v) => { if (!v) handleClose(); }}>
            <DialogContent className="max-w-[480px] p-0 gap-0 overflow-hidden border border-white/10 bg-black text-white shadow-2xl">
                {/* Header — shadcn-style: bg black, text white */}
                <DialogHeader className="px-5 py-4 border-b border-white/10 flex-row items-center gap-3 space-y-0">
                    <div className="h-8 w-8 rounded-lg bg-white/10 flex items-center justify-center shrink-0">
                        <Download className="h-4 w-4 text-white" />
                    </div>
                    <div className="flex-1 min-w-0">
                        <DialogTitle className="text-[13px] font-semibold text-white">Import Database Schema</DialogTitle>
                        <p className="text-[10.5px] text-white/50 mt-0.5 font-mono truncate">{databaseName}</p>
                    </div>
                    <Button variant="ghost" size="icon" className="h-6 w-6 shrink-0 text-white/50 hover:text-white hover:bg-white/10" onClick={handleClose}>
                        <X className="h-3.5 w-3.5" />
                    </Button>
                </DialogHeader>

                {/* Body */}
                <div className="flex flex-col" style={{ maxHeight: "58vh" }}>

                    {/* Loading */}
                    {phase === "loading-schemas" && (
                        <div className="flex flex-col items-center justify-center py-14 gap-3 text-center">
                            <Loader2 className="h-6 w-6 animate-spin text-white/50" />
                            <p className="text-[12px] text-white/50">Fetching schemas…</p>
                        </div>
                    )}

                    {/* Schema picker */}
                    {phase === "selecting" && (
                        <>
                            <div className="px-5 pt-4 pb-2 shrink-0 space-y-3">
                                <p className="text-[11.5px] text-white/60 leading-relaxed">
                                    Select schemas to import. Each schema becomes a folder with
                                    <span className="text-white/80"> tables</span>,
                                    <span className="text-white/80"> views</span>,
                                    <span className="text-white/80"> functions</span>, indexes, and more.
                                </p>
                                <button
                                    className="flex items-center gap-2 text-[11px] text-white/50 hover:text-white/80 transition-colors"
                                    onClick={toggleAll}
                                >
                                    <Checkbox
                                        checked={allSelected}
                                        onCheckedChange={toggleAll}
                                        className="h-3.5 w-3.5"
                                        onClick={(e) => e.stopPropagation()}
                                    />
                                    {allSelected ? "Deselect all" : "Select all"} ({schemas.length} schemas)
                                </button>
                            </div>

                            <ScrollArea className="flex-1 min-h-0 px-3 pb-3">
                                <div className="space-y-0.5">
                                    {schemas.map((s) => (
                                        <SchemaRow key={s.name} schema={s} onToggle={toggleSchema} />
                                    ))}
                                    {schemas.length === 0 && (
                                        <div className="text-center py-8 text-[12px] text-white/35">
                                            No schemas found
                                        </div>
                                    )}
                                </div>
                            </ScrollArea>
                        </>
                    )}

                    {/* Importing */}
                    {phase === "importing" && progress && (
                        <div className="flex flex-col items-center justify-center py-12 gap-5 px-8 text-center">
                            <div className="relative h-16 w-16 flex items-center justify-center">
                                <CircularProgress value={progress.current} max={progress.total} />
                                <Database className="absolute h-5 w-5 text-white/60" />
                            </div>
                            <div className="space-y-1.5 w-full">
                                <p className="text-[12.5px] font-medium text-white/90">{progress.message}</p>
                                <p className="text-[10.5px] text-white/40 font-mono">
                                    {progress.current} / {progress.total} schemas
                                </p>
                            </div>
                            <div className="w-full bg-white/15 rounded-full h-1 overflow-hidden">
                                <div
                                    className="h-full bg-white/60 rounded-full transition-[width] duration-500 ease-out"
                                    style={{ width: `${(progress.current / Math.max(progress.total, 1)) * 100}%` }}
                                />
                            </div>
                        </div>
                    )}

                    {/* Done */}
                    {phase === "done" && importResult && (
                        <div className="flex flex-col gap-3 px-5 py-4">
                            <div className="flex items-center gap-2.5">
                                <div className="h-7 w-7 rounded-full bg-emerald-500/20 flex items-center justify-center shrink-0">
                                    <CheckCircle2 className="h-4 w-4 text-emerald-400" />
                                </div>
                                <div>
                                    <p className="text-[12.5px] font-semibold text-white">Import complete</p>
                                    <p className="text-[10.5px] text-white/50">
                                        Files are now in the Explorer sidebar
                                    </p>
                                </div>
                            </div>
                            <ScrollArea style={{ maxHeight: "calc(58vh - 160px)" }}>
                                <ResultSummary result={importResult} />
                            </ScrollArea>
                        </div>
                    )}

                    {/* Error — user-friendly message + black bg / white text */}
                    {phase === "error" && errorFormatted && (
                        <div className="flex flex-col items-center justify-center py-10 gap-4 px-6 text-center">
                            <div className="h-10 w-10 rounded-full bg-red-500/20 flex items-center justify-center border border-red-500/30">
                                <AlertCircle className="h-5 w-5 text-red-400" />
                            </div>
                            <div className="space-y-2 max-w-sm">
                                <p className="text-[13px] font-semibold text-white">{errorFormatted.title}</p>
                                <p className="text-[12px] text-white/70 leading-relaxed">{errorFormatted.description}</p>
                                {errorFormatted.technical && (
                                    <details className="mt-2 text-left">
                                        <summary className="text-[11px] text-white/50 cursor-pointer hover:text-white/70">
                                            Technical details
                                        </summary>
                                        <pre className="mt-1.5 p-2.5 rounded-md bg-white/5 border border-white/10 text-[10px] text-white/60 font-mono break-all overflow-x-auto">
                                            {errorFormatted.technical}
                                        </pre>
                                    </details>
                                )}
                            </div>
                            <div className="flex gap-2">
                                <Button
                                    size="sm"
                                    className="gap-1.5 h-8 text-xs bg-white text-black hover:bg-white/90 border-0"
                                    onClick={() => { setPhase("loading-schemas"); loadSchemas(); }}
                                >
                                    <RefreshCw className="h-3 w-3" /> Retry
                                </Button>
                                <Button
                                    size="sm"
                                    variant="outline"
                                    className="gap-1.5 h-8 text-xs border-white/20 text-white hover:bg-white/10"
                                    onClick={handleClose}
                                >
                                    Cancel
                                </Button>
                            </div>
                        </div>
                    )}
                </div>

                {/* Footer — shadcn-style black/white */}
                <div className="px-5 py-3 border-t border-white/10 flex items-center justify-between shrink-0 bg-white/5">
                    <span className="text-[10px] text-white/40 font-mono">
                        {phase === "selecting" && `${selectedCount} of ${schemas.length} selected`}
                        {phase === "done" && importResult && (
                            `${importResult.total_tables}T · ${importResult.total_views}V · ${importResult.total_functions}F`
                        )}
                    </span>
                    <div className="flex gap-2">
                        {phase !== "importing" && (
                            <Button
                                size="sm"
                                variant="ghost"
                                className="h-7 text-xs text-white/60 hover:text-white hover:bg-white/10"
                                onClick={handleClose}
                            >
                                {phase === "done" ? "Close" : "Cancel"}
                            </Button>
                        )}
                        {phase === "selecting" && (
                            <Button
                                size="sm"
                                className="h-7 text-xs gap-1.5 bg-white text-black hover:bg-white/90 border-0"
                                onClick={handleImport}
                                disabled={selectedCount === 0}
                            >
                                <Download className="h-3.5 w-3.5" />
                                Import {selectedCount > 0 && `${selectedCount} schema${selectedCount !== 1 ? "s" : ""}`}
                            </Button>
                        )}
                        {phase === "done" && (
                            <Button size="sm" className="h-7 text-xs gap-1.5 bg-emerald-600 hover:bg-emerald-500 text-white border-0" onClick={handleClose}>
                                <CheckCircle2 className="h-3.5 w-3.5" />
                                Done
                            </Button>
                        )}
                    </div>
                </div>
            </DialogContent>
        </Dialog>
    );
}
