"use client";

import { useState, useMemo, useCallback } from "react";
import { useSchemaDesignerStore } from "@/stores/schema-designer-store";
import { generateSQL } from "@/lib/schema-designer-engine";
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import {
    FileDown,
    Copy,
    CheckCircle2,
    FileCode,
    FileJson,
    FileText,
} from "lucide-react";
import { toast } from "sonner";

interface SchemaExportProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
}

type ExportFormat = "sql" | "migration" | "json";

export function SchemaExport({ open, onOpenChange }: SchemaExportProps) {
    const { getActiveProject } = useSchemaDesignerStore();
    const project = getActiveProject();
    const [format, setFormat] = useState<ExportFormat>("sql");
    const [copied, setCopied] = useState(false);

    const exportContent = useMemo(() => {
        if (!project) return "";

        switch (format) {
            case "sql":
                return generateSQL(project.tables);

            case "migration": {
                const timestamp = new Date().toISOString().replace(/\D/g, "").slice(0, 14);
                const upSql = generateSQL(project.tables);
                const downSql = project.tables
                    .map(t => `DROP TABLE IF EXISTS "${t.name}" CASCADE;`)
                    .reverse()
                    .join("\n");
                return `-- Migration: ${timestamp}_create_${project.name.replace(/\s+/g, "_").toLowerCase()}
-- Generated by HelixDB Schema Designer

-- ╔══════════════════════════════════════╗
-- ║            UP MIGRATION              ║
-- ╚══════════════════════════════════════╝

${upSql}

-- ╔══════════════════════════════════════╗
-- ║           DOWN MIGRATION             ║
-- ╚══════════════════════════════════════╝

${downSql}
`;
            }

            case "json":
                return JSON.stringify(
                    {
                        project: project.name,
                        app_type: project.app_type,
                        tables: project.tables.map(t => ({
                            name: t.name,
                            columns: t.columns.map(c => ({
                                name: c.name,
                                type: c.data_type,
                                nullable: c.nullable,
                                default: c.default_value,
                                primary_key: c.is_primary_key,
                                foreign_key: c.foreign_key
                                    ? (() => {
                                        const targetTable = project.tables.find(tt => tt.id === c.foreign_key!.target_table_id);
                                        const targetCol = targetTable?.columns.find(cc => cc.id === c.foreign_key!.target_column_id);
                                        return targetTable && targetCol
                                            ? {
                                                table: targetTable.name,
                                                column: targetCol.name,
                                                on_delete: c.foreign_key?.on_delete ?? "CASCADE",
                                                on_update: c.foreign_key?.on_update ?? "CASCADE",
                                            }
                                            : null;
                                    })()
                                    : null,
                            })),
                        })),
                        generated_at: new Date().toISOString(),
                    },
                    null,
                    2
                );

            default:
                return "";
        }
    }, [project, format]);

    const handleCopy = useCallback(async () => {
        await navigator.clipboard.writeText(exportContent);
        setCopied(true);
        toast.success("Copied to clipboard!");
        setTimeout(() => setCopied(false), 2000);
    }, [exportContent]);

    const handleDownload = useCallback(() => {
        const ext = format === "json" ? "json" : "sql";
        const mimeType = format === "json" ? "application/json" : "text/plain";
        const blob = new Blob([exportContent], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${project?.name?.replace(/\s+/g, "_").toLowerCase() ?? "schema"}.${ext}`;
        a.click();
        URL.revokeObjectURL(url);
        toast.success("File downloaded!");
    }, [exportContent, format, project]);

    if (!project) return null;

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-xl max-h-[80vh]">
                <DialogHeader>
                    <DialogTitle className="flex items-center gap-2">
                        <FileDown className="h-4 w-4 text-emerald-500" />
                        Export Schema
                    </DialogTitle>
                </DialogHeader>

                {/* Format selector */}
                <div className="flex items-center gap-2 mb-3">
                    <button
                        onClick={() => setFormat("sql")}
                        className={`flex items-center gap-1.5 rounded-md px-3 py-2 text-xs font-medium transition-all border ${format === "sql"
                            ? "bg-emerald-500/10 border-emerald-500/30 text-emerald-500"
                            : "bg-muted/20 border-border/20 text-muted-foreground hover:text-foreground"
                            }`}
                    >
                        <FileCode className="h-3.5 w-3.5" />
                        SQL DDL
                    </button>
                    <button
                        onClick={() => setFormat("migration")}
                        className={`flex items-center gap-1.5 rounded-md px-3 py-2 text-xs font-medium transition-all border ${format === "migration"
                            ? "bg-emerald-500/10 border-emerald-500/30 text-emerald-500"
                            : "bg-muted/20 border-border/20 text-muted-foreground hover:text-foreground"
                            }`}
                    >
                        <FileText className="h-3.5 w-3.5" />
                        Migration
                    </button>
                    <button
                        onClick={() => setFormat("json")}
                        className={`flex items-center gap-1.5 rounded-md px-3 py-2 text-xs font-medium transition-all border ${format === "json"
                            ? "bg-emerald-500/10 border-emerald-500/30 text-emerald-500"
                            : "bg-muted/20 border-border/20 text-muted-foreground hover:text-foreground"
                            }`}
                    >
                        <FileJson className="h-3.5 w-3.5" />
                        JSON
                    </button>
                </div>

                {/* Preview */}
                <div className="relative rounded-lg border border-border/20 bg-muted/10 overflow-hidden">
                    <pre className="text-[11px] font-mono text-muted-foreground p-4 overflow-auto max-h-[40vh] whitespace-pre-wrap">
                        {exportContent || "No tables to export."}
                    </pre>
                </div>

                {/* Actions */}
                <div className="flex items-center gap-2 justify-end mt-2">
                    <Button variant="outline" size="sm" onClick={handleCopy} className="gap-1.5 text-xs">
                        {copied ? <CheckCircle2 className="h-3 w-3 text-emerald-500" /> : <Copy className="h-3 w-3" />}
                        {copied ? "Copied!" : "Copy"}
                    </Button>
                    <Button
                        size="sm"
                        onClick={handleDownload}
                        className="gap-1.5 text-xs bg-emerald-600 hover:bg-emerald-700 text-white"
                    >
                        <FileDown className="h-3 w-3" />
                        Download
                    </Button>
                </div>
            </DialogContent>
        </Dialog>
    );
}
