#!/bin/sh
# Run `pnpm tauri ios dev` with a dev-host IP that devices can actually reach.
# Tauri often picks 192.0.0.2 (USB); many setups work more reliably over Wi‑Fi using
# the Mac's default-route IPv4. Writes gen/apple/.xcode.env.local so Xcode rebuilds match.
set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT" || exit 1

APPLE_DIR="$ROOT/src-tauri/gen/apple"
mkdir -p "$APPLE_DIR"

# Manual override: PGSTUDIO_IOS_DEV_HOST=192.168.x.x pnpm ios:dev:open
# Simulator: PGSTUDIO_IOS_SIMULATOR=1 skips forced IP (Tauri uses localhost path).
if [ "${PGSTUDIO_IOS_SIMULATOR:-0}" = "1" ]; then
  echo "iOS dev (simulator): PGSTUDIO_IOS_SIMULATOR=1 — not forcing --host IP" >&2
  exec pnpm tauri ios dev "$@"
fi

if [ ! -f "$ROOT/scripts/lib/resolve-ios-dev-host.sh" ]; then
  echo "error: missing $ROOT/scripts/lib/resolve-ios-dev-host.sh" >&2
  exit 1
fi
# shellcheck disable=SC1090
. "$ROOT/scripts/lib/resolve-ios-dev-host.sh"

if ! IP="$(pgstudio_resolve_mac_lan_ipv4)"; then
  echo "error: Could not resolve a Mac LAN IPv4 for iPad/iPhone dev." >&2
  echo "  Do not use 192.0.0.2 on device: iPadOS routes it via lo0 (NW -1004), not to your Mac." >&2
  echo "  Connect Mac + iPad to Wi‑Fi, or set PGSTUDIO_IOS_DEV_HOST / PGSTUDIO_IOS_ALLOW_USB_HOST=1" >&2
  exit 1
fi

{
  echo "# Generated by scripts/ios-dev.sh — do not edit by hand."
  echo "export TAURI_DEV_HOST=\"$IP\""
} >"$APPLE_DIR/.xcode.env.local"

echo "iOS dev: TAURI_DEV_HOST=$IP — Tauri will embed this in devUrl (not 192.0.0.2)." >&2
echo "iOS dev: If Xcode logs still show 192.0.0.2, quit old \`tauri ios dev\`, run this script again, then Xcode Product → Clean Build Folder." >&2

exec pnpm tauri ios dev --host "$IP" "$@"
